apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-notification-
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: notification
          image: curlimages/curl
      command:
        - "curl"
        - "-X"
        - "POST -H 'Content-type: application/json'"
        - --data '{"text":"Hello from curl command!"}' https://api.flock.com/hooks/sendMessage/b450fe5f-e66a-446a-bc4f-76b6484c30a6
  restartPolicy: Never
  backoffLimit: 2
